name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main  # Trigger only on PR merges to main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # adjust to your project

      - name: Restore dependencies
        run: dotnet restore

      - name: Calculate Version
        id: version
        run: |
          DATE=$(date +'%Y%m%d')
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)
          VERSION="1.0.$DATE.$SHORT_SHA"
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Calculated version: $VERSION"

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet package
        run: |
          dotnet pack --configuration Release --no-build \
            -p:PackageVersion=$PACKAGE_VERSION \
            -o ./artifacts

      - name: Publish to NuGet
        run: dotnet nuget push ./artifacts/*.nupkg \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json
